apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
data:
  # Use the following file for reference http://download.redis.io/redis-stable/redis.conf
  redis.conf: |
    include /overrides/redis.conf

    protected-mode no
    port 6379
    tcp-backlog 511
    loglevel notice
    logfile ""
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data/db
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    cluster-enabled yes
    cluster-config-file nodes-6379.conf
    cluster-node-timeout 15000
