apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    name: redis-sentinel-node
    role: master
