apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  labels:
    name: redis-sentinel
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
  selector:
    name: redis-sentinel-node
