apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  serviceName: redis-cluster
  replicas: 6
  template:
    metadata:
      labels:
        name: redis-cluster-node
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        # Redis
        - name: redis
          image: redis
          args:
            - /config/redis.conf
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data/db
            - name: redis-cluster-config
              mountPath: /config
            - name: redis-cluster-overrides
              mountPath: /overrides

        # Sidecar
        - name: sidecar
          image: commercialtribe/redis-cluster-sidecar:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: pod-info
              mountPath: /etc/pod-info
      volumes:
        - name: pod-info
          downwardAPI:
            items:
              - path: labels
                fieldRef:
                  fieldPath: metadata.labels
        - name: redis-cluster-config
          configMap:
            name: redis-cluster
            items:
              - key: redis.conf
                path: redis.conf
        - name: redis-cluster-overrides
          configMap:
            name: redis-cluster-overrides
            items:
              - key: redis.conf
                path: redis.conf
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        annotations:
          volume.beta.kubernetes.io/storage-class: "ssd"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
